environment:
  APP_VERSION: '2.1'
  matrix:
    - PYTHON_VER: C:\Python27\python
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      SETUP_COMPILER_FLAG: --compiler=mingw32
    - PYTHON_VER: C:\Python35\python
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      SETUP_COMPILER_FLAG:
    - PYTHON_VER: C:\Python37\python
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      SETUP_COMPILER_FLAG:


version: '$(APP_VERSION).{build}'

image: Visual Studio 2017

install:
  - set PATH=%PATH%;C:\msys64\mingw32\bin
  # We need wheel installed to build wheels
  - "%PYTHON_VER%.exe -m pip install wheel"

build_script:
  - cd miniupnpc
  - appveyor AddCompilationMessage "Building miniupnpc"
  - mingw32-make -f Makefile.mingw
  - mingw32-make -f Makefile.mingw pythonmodule PYTHON=%PYTHON_VER%

after_build:
  - 7z a -x!wingenminiupnpcstrings.exe ..\miniupnpc-%APPVEYOR_BUILD_VERSION%.zip *.exe *.dll *.a *.lib

artifacts:
  - path: miniupnpc-$(appveyor_build_version).zip
    name: miniupnpc binaries
  - path: miniupnpc/dist/miniupnpc-*.whl
    name: miniupnpc python wheel (self-contained)
  - path: miniupnpc/dist/miniupnpc-*.egg
    name: miniupnpc python egg (self-contained)
